name: SauceIn
description: A plugin designed for an all-op server and gives memories of the old TotalFreedom IP address.
version: 1.1
main: me.superischroma.saucein.SauceIn
author: [Super_]
depend: [Aero]
commands:
    creative:
        description: Creative gamemode management.
        usage: /<command> [player]
        aliases: [gmc]
    survival:
        description: Survival gamemode management.
        usage: /<command> [player]
        aliases: [gms]
    totalfreedom:
        description: Tells the sender about the TotalFreedom server
        usage: /<command>
        aliases: [tf]
    opall:
        description: Gives operator to all players on the server
        usage: /<command> [-c | -s | -a]
    deopall:
        description: Revokes operator from all players on the server
        usage: /<command>
    op:
        description: Gives operator to the player described
        usage: /<command> <player>
    deop:
        description: Revokes operator from the player described
        usage: /<command> <player>
    opme:
        description: Gives operator to the sender
        usage: /<command>
    list:
        description: List of players
        usage: /<command>
    rank:
        description: Shows the rank of the player described
        usage: /<command> [player]
    adminchat:
        description: Toggle adminchat.
        usage: /<command>
    saucein:
        description: Main command.
        usage: /<command> [reload]
# As of now, permissions aren't used. They might be used in the future, though.